trax_vehicle_manager/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('trax_vehicle_manager_data.urls')),
    path('admin/', admin.site.urls),
    
]

trax_vehicle_manager_data/urls.py
#<------- imported libraries ----------
#django admin
from django.contrib import admin

#path,include
from django.urls import path,re_path

#</------- imported libraries ---------


#<-------- importing view -------------

from trax_vehicle_manager_data import views

#</-------- importing view ------------

#App Name Of Project
app_name='trax_vehicle_manager_data'

urlpatterns = [
    #Create your URLs here.

    #<----------- Authentication URLs ---------------

    #url for login page
    path("login",views.user_login,name='login'),
    
    #url for Register page
    path('register',views.user_sign_up,name='register'),

    # Logout
    path('logout/', views.user_sign_out, name='logout'),

    #url for forgot password page
    path('forgetpassword',views.forgetpassword,name='forgetpassword'),
    
    #</----------- Authentication URLs ---------------


    #<------------ Projects Page URLs ----------------


    #url for importing excel 
    path('import',views.fileimport,name='import'),

    #url for vehicle list page
    path('vehicles',views.vehicles,name='vehicles'),

    #url for update a vehicle
    path('vehicles/update_vehicle_data/<int:pk>',views.VehicleUpdateView.as_view(), name='update_vehicle_data'),   
    
    #url for delete a vehicle
    path('vehicles/delete_vehicle_data/<int:pk>', views.VehicleDeleteView.as_view(), name='delete_vehicle_data'),

    #url for add a new vehicle 
    path('vehicles/vehicle_create',views.Create_New_Vehicle.as_view(),name='vehicle_create'),

    #url for driver master page
    path('driver/driver_master',views.driver_master,name='driver_master'),

    #url for add a new driver
    path('driver/driver_master/create',views.Create_New_Driver.as_view(),name='driver_master_create'),

    #url for update a driver in driver master
    path('driver/driver_master/update_driver_data/<int:pk>', views.DriverUpdateView.as_view(), name='update_driver_data'),   

    #url for delete a driver in driver master
    path('driver/driver_master/delete_driver_data/<int:pk>', views.DriverDeleteView.as_view(), name='delete_driver_data'),

    #url for Read Driver KYC Data on Driver Master Page
    path('driver/driver_master/read_driver_kyc_data/<int:pk>', views.DriverKYCFormReadView.as_view(), name='read_driver_kyc_data'),

    #url for driver odometer page
    path('driver/driver_odometer',views.driver_odometer,name='driver_odometer'),

    #url for driver odometer update view 
    path('driver/driver_odometer/update_driver_odometer_data/<int:pk>', views.DriverOdometerUpdateView.as_view(), name='update_driver_odometer_data'),

    #url for driver odometer delete view 
    path('driver/driver_odometer/delete_driver_odometer_data/<int:pk>', views.DriverOdometerDeleteView.as_view(), name='delete_driver_odometer_data'),

    #url for driver Usage page
    path('driver/drivers_usage',views.drivers_usage,name='drivers_usage'),

    #url for driver Details page
    path('driver/drivers_details/<int:pk>',views.drivers_details,name='drivers_details'),
    
    #url for driver form page
    path('',views.drivers_odometer_form,name='drivers_odometer_form'),
    
    #url for driver form submit page
    path('drivers_odometer_form_submit',views.drivers_odometer_form_submit,name='drivers_odometer_form_submit'),
    
    #url for driver successfull message form page
    path('driver/drivers_odometer_successfull_form',views.drivers_odometer_successfull_form,name='drivers_odometer_successfull_form'),
    
    #url for Diesel details page
    path('diesel/full_diesel_details',views.full_diesel_details,name='full_diesel_details'),

    #url for Full Diesel details page filtered by date
    path('diesel/full_diesel_details_filtered_by_date',views.full_diesel_details_filtered_by_date,name='full_diesel_details_filtered_by_date'),

    #url for full diesel detail odometer update view
    path('diesel/full_diesel_details_filtered_by_date/update_diesel_odometer_reading/<int:pk>', views.DieselOdometerReadingUpdateView.as_view(), name='update_diesel_odometer_reading'),
    
    #url for Upload Diesel Data Form
    path('diesel/diesel_data_create_form', views.Upload_Diesel_Data_Form.as_view(), name='diesel_data_create_form'),
    
    #url for Diesel Transaction details page
    path('diesel/diesel_transaction_details',views.diesel_transaction_details,name='diesel_transaction_details'),
    
    #url for vehicle diesel report page
    path('diesel/vehicle_diesel_report',views.vehicle_diesel_report,name='vehicle_diesel_report'),

    #url for details of one vehicle diesel report 
    path('diesel/vehicle_diesel_report/one_vehicle/<int:pk>',views.vehicle_diesel_report_one_vehicle,name='vehicle_diesel_report_one_vehicle'),
    
    #url for Diesel Transaction Tally page
    path('diesel/transaction_tally',views.transaction_tally,name='transaction_tally'),
    
    #url for Diesel delete page
    path('diesel/diesel_delete_data',views.diesel_delete_data,name='diesel_delete_data'),    

    #url for Maintenance data page
    path('maintenance/maintenance_data',views.maintenance_data,name='maintenance_data'),
    
    #url for Upload Maintenance Form
    path('maintenance/upload_maintenance_form', views.Upload_New_Maintenance_Form.as_view(), name='upload_maintenance_form'),

    #url for Read Maintenance Data
    path('maintenance/read_maintenance_data/<int:pk>', views.MaintenanceReadView.as_view(), name='read_maintenance_data'),

    #url for Update Maintenance Data
    path('maintenance/update_maintenance_data/<int:pk>', views.MaintenanceUpdateView.as_view(), name='update_maintenance_data'),    

    #url for Delete Maintenance Data
    path('maintenance/delete_maintenance_data/<int:pk>', views.MaintenanceDeleteView.as_view(), name='delete_maintenance_data'),    

    #url for maintenance details page
    path('maintenance/maintenance_details/',views.maintenance_details,name='maintenance_details'),

    #url for maintenance details form Submit
    path('maintenance/maintenance_details/maintenance_details_form_submit/', views.maintenance_details_form_submit, name='maintenance_details_form_submit'),

    #url for maintenance summary for one vehicle 
    path('maintenance/maintenance_details/one_vehicle/<int:pk>',views.maintenance_summary_one_vehicle,name='maintenance_summary_one_vehicle'),
    
    #url for maintenance update payment page
    path('maintenance/maintenance_update_payment',views.maintenance_update_payment,name='maintenance_update_payment'),

    #url for maintenance details for one company 
    re_path(r'^maintenance/maintenance_update_payment/one_dealer/(?P<dealer_name>\w+)/$',views.maintenance_summary_one_company,name='maintenance_summary_one_company'),

    #url for Read Maintenance Data on Delete Page
    path('maintenance/read_maintenance_data_on_delete_page/<int:pk>', views.MaintenanceReadOnDeletePageView.as_view(), name='read_maintenance_data_on_delete_page'),

    #url for Maintenance delete page
    path('maintenance/maintenance_delete_data',views.maintenance_delete_data,name='maintenance_delete_data'),   

    #url for Maintenance Company Show Report
    path('maintenance/maintenance_details/maintenance_company_show_report',views.maintenance_company_show_report,name='maintenance_company_show_report'),  

    #url for Maintenance data delete within given bill date
    #re_path(r'^maintenance/maintenance_delete_data/',views.maintenance_delete_within_date,name='maintenance_delete_within_date'), 

    #url for recurring expense puc page
    path('recurring_expense/puc',views.recurring_expense_puc,name='recurring_expense_puc'),

    path('recurring_expense/puc/delete/<int:pk>', views.RecurringExpensePUCDeleteView.as_view(), name='delete_recurring_expense_puc'),    

    path('recurring_expense/puc/update/<int:pk>', views.RecurringExpensePUCUpdateView.as_view(), name='update_recurring_expense_puc'),  

    path('recurring_expense/puc/create',views.RecurringExpensePUCCreateView.as_view(),name='puc_create'),

    #url for recurring expense oilchange page
    path('recurring_expense/oilchange',views.recurring_expense_oilchange,name='recurring_expense_oilchange'),
    
    path('recurring_expense/oilchange/update/<int:pk>', views.RecurringExpenseOilChangeUpdateView.as_view(), name='update_recurring_expense_oilchange'),  

    path('recurring_expense/oilchange/delete/<int:pk>', views.RecurringExpenseOilChangeDeleteView.as_view(), name='delete_recurring_expense_oilchange'),  

    path('recurring_expense/oilchange/create',views.RecurringExpenseOilChangeCreateView.as_view(),name='oilchange_create'),

    #url for recurring expense hubgreasing page
    path('recurring_expense/hubgreasing',views.recurring_expense_hubgreasing,name='recurring_expense_hubgreasing'),

    path('recurring_expense/hubgreasing/update/<int:pk>', views.RecurringExpenseHubGreasingUpdateView.as_view(), name='update_recurring_expense_hubgreasing'),  

    path('recurring_expense/hubgreasing/delete/<int:pk>', views.RecurringExpenseHubGreasingDeleteView.as_view(), name='delete_recurring_expense_hubgreasing'),  

    path('recurring_expense/hubgreasing/create',views.RecurringExpenseHubGreasingCreateView.as_view(),name='hubgreasing_create'),

    #url for insurance claim page
    path('settlement/insurance_claim',views.insurance_claim,name='insurance_claim'),
    
    #url for police settlement page
    path('settlement/police_settlement',views.police_settlement,name='police_settlement'),
   
    #url for mis page
    path('mis',views.mis,name='mis'),
    
    #url for tyres page
    path('tyres',views.tyres,name='tyres'),
   
    #url for supervisor form page
    path('supervisor/supervisor_form',views.supervisor_form,name='supervisor_form'),
   
    #url for supervisor data page
    path('supervisor/supervisor_data',views.supervisor_data,name='supervisor_data'),
    
    #url for supervisor data page
    path('profile',views.profile,name='profile'),
   
    #url for report error page

trax_vehicle_manager_data/forms.py
from django import forms
from trax_vehicle_manager_data.models import CustomUser,Drivers,Cleaners,Vehicles,Expenses,Diesel,Maintenance,GarageBilling,Insurance,PoliceSettlements,RecurringExpenses,PUC,OilChange,Client,Drivers_Odometer_Data,RecurringExpensesModel,PUCRecurringExpenses,OilChangeRecurringExpenses,HubGreasingRecurringExpenses
from bootstrap_modal_forms.forms import BSModalForm

class MaintenanceForm(BSModalForm):
    class Meta:
        model = Maintenance
        fields = ('vehicle_number',
        'vehicle_detail',
        'vehicle_type',
        'chalak_malal',
        'company_name',
        'odometer_reading',
        'bill_number',
        'dealer_part_number',
        'maintenance_dealer_name',
        'particular',
        'particular_details',
        'quantity',
        'rate',
        'amount',
        'discount',
        'tax',
        'tds',
        'labour_charge',
        'total_amount')  

class DriverForm(BSModalForm):
    class Meta:
        model = Drivers
        fields = ('driver_reference_no',
        'driver_driver_name',
        'driver_vehicle_short_number',
        'driver_vehicle_number',
        'driver_vehicle_type',
        'vehicle_type_of_module',
        'driver_license_number',
        'driver_aadhar_number',
        'driver_contact_number',
        'driver_pan_number',
        'driver_address_proof',
        'driver_photoid_proof',
        'driver_driver_bank_name',
        'driver_bank_name',
        'driver_bank_account_number',
        'driver_ban_ifsc_code',
        'driver_bank_branch',
        'driver_alternate_contact_number',
        'driver_license_residence_address',
        'driver_aadhar_card_residence_address',
        'driver_years_of_experience',
        'driver_last_employer_name',
        'driver_years_with_kruze_or_aaron')

class DriverOdometerForm(BSModalForm):
    class Meta:
        model = Drivers_Odometer_Data
        fields = ('drivers_odometer_data_driver_id',
        'drivers_odometer_data_mobile_number',
        'drivers_odometer_data_vehicle_number',
        'drivers_odometer_data_odometer_kilometer',
        'drivers_odometer_data_cleaner_id')

class DieselOdometerReadingUpdateForm(BSModalForm):
    class Meta:
        model = Diesel
        fields = ('odometer_reading',)

class DieselDataForm(BSModalForm):
    class Meta:
        model = Diesel
        fields = ('expense_name',
        'expense_id',
        'expense_vehicle_id',
        'terminal_id',
        'transaction_date',
        'merchant',
        'account_number',
        'card_used',
        'vehicle_number',
        'vehicle_detail',
        'transaction_type',
        'diesel_rate',
        'volume',
        'amount_Rs',
        'balance_Rs',
        'odometer_reading',
        'ownership')

class DriverKYCForm(BSModalForm):
    class Meta:
        model = Drivers
        fields = ('driver_pan_number',
        'driver_address_proof',
        'driver_photoid_proof',
        'driver_driver_bank_name',
        'driver_bank_name',
        'driver_bank_account_number',
        'driver_ban_ifsc_code',
        'driver_bank_branch',
        'driver_license_residence_address',
        'driver_aadhar_card_residence_address',
        'driver_years_of_experience',
        'driver_last_employer_name',
        'driver_years_with_kruze_or_aaron')

class VehicleDataForm(BSModalForm):
    class Meta:
        model = Vehicles
        fields = ('vehicle_ownership_name',
        'vehicle_id',
        'vehicle_number',
        'vehicle_card_number',
        'vehicle_seating_capacity',
        'minimum_average',
        'incremental_average',
        'vehicle_current_status',
        'vehicle_buying_date',
        'vehicle_type',
        'vehicle_ownership',
        'vehicle_ownership_details',
        'vehicle_manufacturer',
        'vehicle_registered_number',
        'driver_id',
        'cleaner_id')

class PUCDataForm(BSModalForm):
    class Meta:
        model = PUCRecurringExpenses
        fields = ('recurring_expense_vehicle_id',
        'puc_number',
        'center_name',
        'test_date',
        'expiry_date',
        'puc_amount',
        'date_of_entry',
        'current_odometer_km',
        'last_odometer_km',
        'current_km_date')

class OilChangeForm(BSModalForm):
    class Meta:
        model = OilChangeRecurringExpenses
        fields = ('recurring_expense_vehicle_id',
        'last_date_of_oil_change',
        'actual_km',
        'minimum_oil_change_km',
        'over_km',
        'date_of_entry',
        'current_odometer_km',
        'last_odometer_km',
        'current_km_date')

class HubGreasingForm(BSModalForm):
    class Meta:
        model = HubGreasingRecurringExpenses
        fields = ('recurring_expense_vehicle_id',
        'last_date_of_hub_greasing',
        'actual_km',
        'minimum_hub_grease_change_km',
        'over_km',
        'date_of_entry',
        'current_odometer_km',
        'last_odometer_km',
        'current_km_date')

trax_vehicle_manager_data/templates/trax_vehicle_manager_data/add_a_new_driver.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Add a New Driver</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Add</button>
  </div>

</form>

trax_vehicle_manager_data/templates/trax_vehicle_manager_data/add_a_new_hubgreasing.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Add a New HubGreasing</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Add</button>
  </div>

</form>

trax_vehicle_manager_data/templates/trax_vehicle_manager_data/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Trax Vehicle Manager</title>
    
    <style>
        #colmn {
            width: 1000px;
        }
    </style>
    
    <!-- Bootstrap CSS CDN -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'trax_vehicle_manager_data/style.css' %}">

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    
    <!-- jQuery CDN - Slim version (=without AJAX) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    

    {% comment %} <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.jqueryui.min.css" />
    
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
   
    {% comment %} <!--jQuery-->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> {% endcomment %}
    
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    
    <!--jQuery-->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    
    <!-- Font Awesome JS -->
    
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    
    {% block stylesheets %}
    {% endblock stylesheets %}
    {% block headscript %}
    {% endblock headscript %}
</head>

<body>
    <div class="wrapper">
        <!-- SIDEBAR  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4>TRAX</h4>
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'trax_vehicle_manager_data:vehicles' %}">Vehicles</a>
                </li>
                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Driver</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:driver_master' %}">Master</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:driver_odometer' %}">Odometer</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:drivers_usage' %}">Usage</a>
                        </li>
                    </ul>
                </li>
                 <li>
                    <a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Diesel</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu1">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:full_diesel_details_filtered_by_date' %}">Full Diesel Details</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:diesel_transaction_details' %}">Transaction Details</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:vehicle_diesel_report' %}">Vehicle Diesel Report</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:transaction_tally' %}">Transaction Tally</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:diesel_delete_data' %}">Delete Data</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Maintenance</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu2">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:maintenance_data' %}">Maintenance Data</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:maintenance_details' %}">Maintenance Details</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:maintenance_update_payment' %}">Update Payment</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:maintenance_delete_data' %}">Delete Data</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Recurring Expenses</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu3">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:recurring_expense_puc' %}">PUC</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:recurring_expense_oilchange' %}">Oil Change</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:recurring_expense_hubgreasing' %}">Hub Greasing</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Settlement</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu4">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:insurance_claim' %}">Insurance Claims</a>
                        </li>
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:police_settlement' %}">Police Settlements</a>
                        </li>

                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu5" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Company MIS</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu5">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:mis' %}">MIS</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu6" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Tyre</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu6">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:tyres' %}">Tyres Data</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#homeSubmenu7" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Supervisors</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu7">
                        <li>
                            <a href="{% url 'trax_vehicle_manager_data:supervisor_data' %}">Supervisor Data</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'trax_vehicle_manager_data:profile' %}">Profile</a>
                </li>
                <li>
                    <a href="{% url 'trax_vehicle_manager_data:report_error' %}">Report Error</a>
                </li>
            </ul>
            <ul class="list-unstyled CTAs">
                <li>
                    <a href="{% url 'trax_vehicle_manager_data:logout' %}" class="btn btn-light">
                        <font color="#1B4965">Logout</font>
                    </a>
                </li>
            </ul>
        </nav>
        <!--SIDEBAR ENDS HERE-->

        <!-- PAGE CONTENT  -->
        <div id="content">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>Menu
                </button>
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
   
    {% block script %}
    {% endblock %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function() {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

    {% block extrascript %}
    {% endblock extrascript %}
</body>

</html>

trax_vehicle_manager_data/templates/trax_vehicle_manager_data/import.html
{% extends 'trax_vehicle_manager_data/base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}